import { VideoInfo } from './types';

// This will be populated after running the upload script
// For now, using placeholder URLs that will be replaced with actual Blob URLs
export const BLOB_VIDEO_BASE_URL = process.env.NEXT_PUBLIC_BLOB_URL || '';

// Helper function to get video URL
export const getBlobVideoUrl = (fileName: string): string => {
  // In production, this will use the actual Blob URLs
  // For development, fall back to local files
  if (BLOB_VIDEO_BASE_URL) {
    return `${BLOB_VIDEO_BASE_URL}/videos/${fileName}`;
  }
  
  // Fallback to local files during development
  return `/videos/full/${fileName}`;
};

// Header videos configuration with Blob URLs
export const HEADER_VIDEOS_BLOB: VideoInfo[] = [
  { src: getBlobVideoUrl('1.mp4'), alt: 'Creative showcase 1' },
  { src: getBlobVideoUrl('2.mp4'), alt: 'Creative showcase 2' },
  { src: getBlobVideoUrl('3.mp4'), alt: 'Creative showcase 3' },
  { src: getBlobVideoUrl('4.mp4'), alt: 'Creative showcase 4' },
  { src: getBlobVideoUrl('5.mp4'), alt: 'Creative showcase 5' },
  { src: getBlobVideoUrl('6.mp4'), alt: 'Creative showcase 6' },
  { src: getBlobVideoUrl('7.mp4'), alt: 'Creative showcase 7' },
  { src: getBlobVideoUrl('8.mp4'), alt: 'Creative showcase 8' },
  { src: getBlobVideoUrl('9.mp4'), alt: 'Creative showcase 9' },
  { src: getBlobVideoUrl('10..mp4'), alt: 'Creative showcase 10' },
  { src: getBlobVideoUrl('11.mp4'), alt: 'Creative showcase 11' },
  { src: getBlobVideoUrl('12.mp4'), alt: 'Creative showcase 12' },
  { src: getBlobVideoUrl('13.mp4'), alt: 'Creative showcase 13' },
  { src: getBlobVideoUrl('14.mp4'), alt: 'Creative showcase 14' },
  { src: getBlobVideoUrl('15.mp4'), alt: 'Creative showcase 15' },
];

// Preview videos for faster initial load (using local files)
export const PREVIEW_VIDEOS_BLOB: VideoInfo[] = [
  { src: '/videos/preview/1.mp4', alt: 'Preview 1' },
  { src: '/videos/preview/2.mp4', alt: 'Preview 2' },
  { src: '/videos/preview/3.mp4', alt: 'Preview 3' },
  { src: '/videos/preview/4.mp4', alt: 'Preview 4' },
  { src: '/videos/preview/5.mp4', alt: 'Preview 5' },
  { src: '/videos/preview/6.mp4', alt: 'Preview 6' },
];

// Dynamic import of blob URLs (generated by upload script)
export const loadBlobUrls = async () => {
  try {
    const blobUrls = await import('./blob-urls.json');
    return blobUrls.default;
  } catch (error) {
    console.warn('Blob URLs not found, using fallback URLs');
    return {};
  }
};